from setuptools import setup, find_packages

setup(
    name="titanic_pipeline",
    version="1.0.0",
    description="Titanic ML Pipeline",
    author="Dagoberto Candeias de Moraes",
    author_email="dagoberto@email.com",
    packages=find_packages(),
    python_requires=">=3.10",
    install_requires=[
        "pandas<3,>=2.1",
        "numpy>=2",
        "scikit-learn",
        "matplotlib",
        "seaborn",
        "xgboost",
        "lightgbm",
        "catboost",
        "scipy",
        "joblib",
        "imbalanced-learn",
        "optuna",
        "pytest",
        "pytest-cov",
        "pytest-mock",
        "pytest-xdist",
        "shap",
        "pre-commit",
        "python-docx",
        "fpdf2",
        "flake8-pyproject",
    ],
)
