name: Run Tests

on:
  push:
    branches: ["main", "master"]
  pull_request:
    branches: ["main", "master"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Conda Environment
        uses: conda-actions/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: 3.11 # Ou a versão especificada no environment.yml
          environment-file: environment.yml
          channel-priority: strict
          activate-environment: titanic_ml

      - name: Install dependencies
        shell: bash -l {0}
        run: |
          echo "Ambiente Conda criado. Instalando o projeto em modo editável..."
          # Instala o projeto como um pacote, o que também instala as dependências do setup.py
          pip install -e .

      - name: Run Pre-commit
        shell: bash -l {0}
        run: |
          pre-commit run --all-files

      - name: Validate Environment
        shell: bash -l {0}
        run: |
          python scripts/validate_environment.py

      - name: Run tests
        shell: bash -l {0}
        run: |
          pytest --cov=. --cov-report=xml

      - name: Upload Relatorio Executivo as artifact
        uses: actions/upload-artifact@v4
        with:
          name: Relatorio_Executivo_Titanic
          path: output/relatorios/Relatorio_Executivo_Titanic.pdf
          if-no-files-found: error
